name: Bug Report
description: Report a bug or crash in DinoX
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please check the [DEBUG guide](https://github.com/rallep71/dinox/blob/master/docs/internal/DEBUG.md) for instructions on how to collect logs.

  - type: dropdown
    id: installation
    attributes:
      label: How did you install DinoX?
      multiple: false
      options:
        - Flatpak
        - AppImage
        - Compiled from source
        - Windows (ZIP from Releases)
        - AppMan / AM
        - Other
    validations:
      required: true

  - type: input
    id: dinox_version
    attributes:
      label: DinoX version
      description: Check About dialog or run `dinox --version`
      placeholder: "0.9.9.2"
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: Operating system and version
      description: e.g. Ubuntu 24.04, Arch Linux, Fedora 41, Windows 11 23H2
      placeholder: "Ubuntu 24.04"
    validations:
      required: true

  - type: input
    id: desktop_environment
    attributes:
      label: Desktop environment (Linux only)
      description: e.g. GNOME 47, KDE Plasma 6, Sway, etc.
      placeholder: "GNOME 47"
    validations:
      required: false

  - type: input
    id: xmpp_server
    attributes:
      label: Used XMPP server (domain)
      description: The domain after the @ in your JID
      placeholder: "chat.example.org"
    validations:
      required: true

  - type: dropdown
    id: xmpp_server_software
    attributes:
      label: Which XMPP server software are you using?
      description: Ask your provider if you're not sure.
      multiple: false
      options:
        - Prosody
        - ejabberd
        - jackal
        - openfire
        - Don't know
        - Other
    validations:
      required: false

  - type: dropdown
    id: encryption
    attributes:
      label: Which encryption was active?
      multiple: false
      options:
        - OMEMO
        - OpenPGP
        - None (unencrypted)
        - Not applicable
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug. What did you expect to happen vs. what actually happened?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: |
        Please attach relevant log output. See the [DEBUG guide](https://github.com/rallep71/dinox/blob/master/docs/internal/DEBUG.md) for how to collect logs.

        **Linux**: `DINO_LOG_LEVEL=debug ./build/main/dinox 2>&1 | tee dinox.log`
        **Flatpak**: `flatpak run --env=DINO_LOG_LEVEL=debug im.github.rallep71.DinoX 2>&1 | tee dinox.log`
        **Windows**: `set DINO_LOG_LEVEL=debug && dinox.exe > dinox.log 2>&1`
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: |
        Anything else? Screenshots, crash reports, related issues?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched [existing issues](https://github.com/rallep71/dinox/issues) for duplicates
          required: true
        - label: I am using the latest version of DinoX
          required: true
        - label: I have read the [DEBUG guide](https://github.com/rallep71/dinox/blob/master/docs/internal/DEBUG.md)
          required: false
